name: 'Get and Cache Dependencies'      
description: 'Get the dependencies (via npm) and cache them'
inputs:
  do-cache:
    description: 'Whether to cache dependencies'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.do-cache == 'true'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: inputs.do-cache != 'true' || steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
